name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: |
        IMAGE_NAME=gilanghuda/dearbaby-app
        TAG=latest
        # Build image with timestamp tag too
        docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
        # Tag image sebagai latest
        docker tag $IMAGE_NAME:$(date +%s) $IMAGE_NAME:$TAG

    - name: Push Docker images
      run: |
        IMAGE_NAME=gilanghuda/dearbaby-app
        TAG=latest
        # Push both timestamp and latest tags
        docker push $IMAGE_NAME:$(date +%s)
        docker push $IMAGE_NAME:$TAG
